"""
Module: characters.py
Berisi data karakter tokoh sejarah beserta atributnya.
"""

# Setiap karakter memiliki atribut True/False untuk digunakan dalam decision tree
CHARACTERS = [
    {
        "name": "Napoleon Bonaparte",
        "asal": "Eropa",
        "pemimpin_militer": True,
        "abad_ke_19": True,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": True,
        "revolusioner": True,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Cleopatra",
        "asal": "Afrika/Mesir",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": True,
        "perempuan": True,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Julius Caesar",
        "asal": "Eropa",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": True,
        "revolusioner": False,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Alexander the Great",
        "asal": "Eropa",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": True,
        "revolusioner": False,
        "pemimpin_negara": True,
        "meninggal_muda": True,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Genghis Khan",
        "asal": "Asia",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": True,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": True,
        "revolusioner": False,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Leonardo da Vinci",
        "asal": "Eropa",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": True,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Isaac Newton",
        "asal": "Eropa",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": True,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Albert Einstein",
        "asal": "Eropa",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": True,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": True,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Marie Curie",
        "asal": "Eropa",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": True,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": True,
        "ilmuwan": True,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Socrates",
        "asal": "Eropa",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": True,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Aristoteles",
        "asal": "Eropa",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": True,
        "filsuf": True,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Confucius",
        "asal": "Asia",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": True,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": True,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Mahatma Gandhi",
        "asal": "Asia",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": True,
        "dari_asia": True,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Abraham Lincoln",
        "asal": "Amerika",
        "pemimpin_militer": False,
        "abad_ke_19": True,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": True,
    },
    {
        "name": "George Washington",
        "asal": "Amerika",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": True,
    },
    {
        "name": "Winston Churchill",
        "asal": "Eropa",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": True,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Adolf Hitler",
        "asal": "Eropa",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": True,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": True,
        "revolusioner": False,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Joseph Stalin",
        "asal": "Eropa",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": True,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Mao Zedong",
        "asal": "Asia",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": True,
        "dari_asia": True,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Nelson Mandela",
        "asal": "Afrika",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": True,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Nabi Muhammad SAW",
        "asal": "Timur Tengah",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": True,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": True,
        "dari_amerika": False,
    },
    {
        "name": "Saladin",
        "asal": "Timur Tengah",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": True,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": True,
        "revolusioner": False,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": True,
        "dari_amerika": False,
    },
    {
        "name": "Soekarno",
        "asal": "Asia",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": True,
        "dari_asia": True,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": True,
        "meninggal_muda": False,
        "beragama_islam": True,
        "dari_amerika": False,
    },
    {
        "name": "Diponegoro",
        "asal": "Asia",
        "pemimpin_militer": True,
        "abad_ke_19": True,
        "abad_ke_20": False,
        "dari_asia": True,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": True,
        "dari_amerika": False,
    },
    {
        "name": "R.A. Kartini",
        "asal": "Asia",
        "pemimpin_militer": False,
        "abad_ke_19": True,
        "abad_ke_20": False,
        "dari_asia": True,
        "dari_timur_tengah": False,
        "perempuan": True,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": False,
        "meninggal_muda": True,
        "beragama_islam": True,
        "dari_amerika": False,
    },
    {
        "name": "Sun Tzu",
        "asal": "Asia",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": True,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": True,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Joan of Arc",
        "asal": "Eropa",
        "pemimpin_militer": True,
        "abad_ke_19": False,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": True,
        "ilmuwan": False,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": False,
        "meninggal_muda": True,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Karl Marx",
        "asal": "Eropa",
        "pemimpin_militer": False,
        "abad_ke_19": True,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": False,
        "filsuf": True,
        "penakluk": False,
        "revolusioner": True,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Charles Darwin",
        "asal": "Eropa",
        "pemimpin_militer": False,
        "abad_ke_19": True,
        "abad_ke_20": False,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": True,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
    {
        "name": "Nikola Tesla",
        "asal": "Eropa",
        "pemimpin_militer": False,
        "abad_ke_19": False,
        "abad_ke_20": True,
        "dari_asia": False,
        "dari_timur_tengah": False,
        "perempuan": False,
        "ilmuwan": True,
        "filsuf": False,
        "penakluk": False,
        "revolusioner": False,
        "pemimpin_negara": False,
        "meninggal_muda": False,
        "beragama_islam": False,
        "dari_amerika": False,
    },
]

def get_all_characters():
    return CHARACTERS

def get_attributes():
    """Mengembalikan daftar semua atribut yang ada (selain 'name' dan 'asal')."""
    if not CHARACTERS:
        return []
    return [key for key in CHARACTERS[0].keys() if key not in ("name", "asal")]
