"""
Module: characters.py
Berisi data karakter tokoh sejarah beserta atributnya.
Atribut diperluas agar decision tree lebih dalam dan akurat.
"""

CHARACTERS = [
    # EROPA - PEMIMPIN MILITER
    {
        "name": "Napoleon Bonaparte",
        "asal": "Eropa",
        "pemimpin_militer": True, "abad_ke_19": True, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": True, "revolusioner": True,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": True, "dari_eropa_barat": True,
        "diasingkan": True, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Otto von Bismarck",
        "asal": "Eropa",
        "pemimpin_militer": True, "abad_ke_19": True, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": True,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": True, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Julius Caesar",
        "asal": "Eropa",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": True, "revolusioner": False,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": True, "dari_eropa_barat": True,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": True,
        "hidup_sebelum_masehi": True, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Alexander the Great",
        "asal": "Eropa",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": True, "revolusioner": False,
        "pemimpin_negara": True, "meninggal_muda": True, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": True, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": True, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Adolf Hitler",
        "asal": "Eropa",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": True, "revolusioner": False,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": True,
        "diasingkan": False, "terlibat_perang_dunia": True, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Joseph Stalin",
        "asal": "Eropa",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": True, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Winston Churchill",
        "asal": "Eropa",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": True,
        "diasingkan": False, "terlibat_perang_dunia": True, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": True, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Joan of Arc",
        "asal": "Eropa",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": True,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": False, "meninggal_muda": True, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": True,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": True,
        "tokoh_agama": True, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": True,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    # EROPA - ILMUWAN / FILSUF
    {
        "name": "Albert Einstein",
        "asal": "Eropa",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": True, "filsuf": False, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": True,
        "diasingkan": True, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Isaac Newton",
        "asal": "Eropa",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": True, "filsuf": True, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": True,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": True,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Marie Curie",
        "asal": "Eropa",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": True,
        "ilmuwan": True, "filsuf": False, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": True,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": True,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Leonardo da Vinci",
        "asal": "Eropa",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": True, "filsuf": False, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": True,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": True, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Charles Darwin",
        "asal": "Eropa",
        "pemimpin_militer": False, "abad_ke_19": True, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": True, "filsuf": False, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": True,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Nikola Tesla",
        "asal": "Eropa",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": True, "filsuf": False, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Socrates",
        "asal": "Eropa",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": True, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": True,
        "hidup_sebelum_masehi": True, "pendiri_negara": False, "tokoh_pendidikan": True,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Aristoteles",
        "asal": "Eropa",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": True, "filsuf": True, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": True, "pendiri_negara": False, "tokoh_pendidikan": True,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Karl Marx",
        "asal": "Eropa",
        "pemimpin_militer": False, "abad_ke_19": True, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": True, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": True,
        "diasingkan": True, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    # ASIA - INDONESIA
    {
        "name": "Soekarno",
        "asal": "Asia",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": True, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": True,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": True, "terlibat_perang_dunia": True, "pahlawan_kemerdekaan": True,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": True,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": True, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": True,
    },
    {
        "name": "Mohammad Hatta",
        "asal": "Asia",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": True, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": True,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": True, "terlibat_perang_dunia": True, "pahlawan_kemerdekaan": True,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": True,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": True, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Pangeran Diponegoro",
        "asal": "Asia",
        "pemimpin_militer": True, "abad_ke_19": True, "abad_ke_20": False,
        "dari_asia": True, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": True,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": True, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": True,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": True,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "R.A. Kartini",
        "asal": "Asia",
        "pemimpin_militer": False, "abad_ke_19": True, "abad_ke_20": False,
        "dari_asia": True, "dari_timur_tengah": False, "perempuan": True,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": False, "meninggal_muda": True, "beragama_islam": True,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": True,
        "tokoh_agama": False, "seniman_atau_sastrawan": True, "dari_indonesia": True,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": True,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Cut Nyak Dien",
        "asal": "Asia",
        "pemimpin_militer": True, "abad_ke_19": True, "abad_ke_20": False,
        "dari_asia": True, "dari_timur_tengah": False, "perempuan": True,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": True,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": True, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": True,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": True,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    # ASIA - LAINNYA
    {
        "name": "Genghis Khan",
        "asal": "Asia",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": True, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": True, "revolusioner": False,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": True, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": True, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Mao Zedong",
        "asal": "Asia",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": True, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": True, "pahlawan_kemerdekaan": True,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": True, "tokoh_pendidikan": False,
        "dari_china": True, "presiden": True,
    },
    {
        "name": "Mahatma Gandhi",
        "asal": "Asia",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": True, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": True,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": True, "mati_terbunuh": True,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Sun Tzu",
        "asal": "Asia",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": True, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": True, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": True, "pendiri_negara": False, "tokoh_pendidikan": True,
        "dari_china": True, "presiden": False,
    },
    {
        "name": "Confucius",
        "asal": "Asia",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": True, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": True, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": False, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": True, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": True, "pendiri_negara": False, "tokoh_pendidikan": True,
        "dari_china": True, "presiden": False,
    },
    # TIMUR TENGAH
    {
        "name": "Nabi Muhammad SAW",
        "asal": "Timur Tengah",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": True, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": True,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": True, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": True, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": True, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Saladin",
        "asal": "Timur Tengah",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": True, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": True, "revolusioner": False,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": True,
        "dari_amerika": False, "kaisar_atau_raja": True, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    {
        "name": "Cleopatra",
        "asal": "Afrika/Mesir",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": True, "perempuan": True,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": True, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": False,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": True, "dari_india": False, "mati_terbunuh": True,
        "hidup_sebelum_masehi": True, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
    # AFRIKA
    {
        "name": "Nelson Mandela",
        "asal": "Afrika",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": False, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": True, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": True,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": True, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": True,
    },
    # AMERIKA
    {
        "name": "Abraham Lincoln",
        "asal": "Amerika",
        "pemimpin_militer": False, "abad_ke_19": True, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": False,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": True, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": True,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": True,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": True,
    },
    {
        "name": "George Washington",
        "asal": "Amerika",
        "pemimpin_militer": True, "abad_ke_19": False, "abad_ke_20": False,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": True, "meninggal_muda": False, "beragama_islam": False,
        "dari_amerika": True, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": True,
        "tokoh_agama": False, "seniman_atau_sastrawan": False, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": False,
        "hidup_sebelum_masehi": False, "pendiri_negara": True, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": True,
    },
    {
        "name": "Martin Luther King Jr.",
        "asal": "Amerika",
        "pemimpin_militer": False, "abad_ke_19": False, "abad_ke_20": True,
        "dari_asia": False, "dari_timur_tengah": False, "perempuan": False,
        "ilmuwan": False, "filsuf": False, "penakluk": False, "revolusioner": True,
        "pemimpin_negara": False, "meninggal_muda": True, "beragama_islam": False,
        "dari_amerika": True, "kaisar_atau_raja": False, "dari_eropa_barat": False,
        "diasingkan": False, "terlibat_perang_dunia": False, "pahlawan_kemerdekaan": True,
        "tokoh_agama": True, "seniman_atau_sastrawan": True, "dari_indonesia": False,
        "dari_afrika": False, "dari_india": False, "mati_terbunuh": True,
        "hidup_sebelum_masehi": False, "pendiri_negara": False, "tokoh_pendidikan": False,
        "dari_china": False, "presiden": False,
    },
]


def get_all_characters():
    return CHARACTERS


def get_attributes():
    """Mengembalikan daftar semua atribut yang ada (selain 'name' dan 'asal')."""
    if not CHARACTERS:
        return []
    return [key for key in CHARACTERS[0].keys() if key not in ("name", "asal")]
